export enum BuiltinType {
	Begin = 1,
	End = 2,
	Item = 3,
	Section = 4,
	Subsection = 5,
	Subsubsection = 6,
	Paragraph = 7,
	Subparagraph = 8,
	Chapter = 9,
	Part = 10,
	Title = 11,
	Author = 12,
	Date = 13,
	TableOfContents = 14,
	Label = 15,
	Ref = 16,
	Include = 17,
	Input = 18,
	Usepackage = 19,
	Documentclass = 20,
	Math = 21,
	DisplayMath = 22,
	InlineMath = 23,
	DisplayInlineMath = 24,
}
